---
title: "Some things I learned this quarter"
subtitle: "FISH 549"
author: "Kali Stone<br>kaliw2@uw.edu"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction

## About Me | Personal

- Born in Fairbanks, Alaska
- Give me Indian food or pizza and I'm a happy camper
- I think otters are absolutely adorable

## About Me | Academic

- University of Washington
- B.S. Aquatic and Fishery Sciences
- Minor in Marine Biology

# Data Science

## Course topics | 3 things I enjoyed learning about

1. How to use Github!
2. Excited to dive into the packages recommended
3. Tips for how to revamp individual and team workflows to be more efficient and help my future self.

## Course topics | 3 things I'd like to learn more about

1. How to stay up to date with the newest packages or best packages for a given application. 
2. More time on Shiny and databases would be great!
3. Workshops or ways to do something for my work group, I think they would really benefit from a lot of this information (and from a non-me source)

## {data-background=img/fam.jpg data-background-size=cover}

